version: "3.7"
services:
  my_web_app:
    image: my_web_app:latest
    ports:
      - "8088:8088"
    networks:
        - network2
    environment:
      MONGO_URL_RUN: "mongodb://10.100.1.143:20000"

  mongo:
    image: my_mongodb:latest
    ports:
      - "27017:27017"
    networks:
      - network2
    environment:
      MONGO_URL_RUN: "mongodb://10.100.1.143:20000"

networks:
  network2: {}


volumes:
  volume_demo:
  volume_demo2:
